### ISSUE TITLE
onItemSelected NullPointerException

### ISSUE THREAD

**Issue by philipgiuliani** [dextorer/Sofa#11]
The most reported error of my AndroidTV app is the following. I hope you/somebody can fix this bug!

```
Fatal Exception: java.lang.NullPointerException
       at com.sgottard.sofa.BrowseFragment$9.onItemSelected(BrowseFragment.java:821)
       at android.support.v17.leanback.widget.RowPresenter.dispatchItemSelectedListener(RowPresenter.java:470)
       at android.support.v17.leanback.widget.ListRowPresenter.dispatchItemSelectedListener(ListRowPresenter.java:441)
       at android.support.v17.leanback.widget.RowPresenter.createRowViewHolder(RowPresenter.java:481)
       at android.support.v17.leanback.widget.ListRowPresenter.onRowViewSelected(ListRowPresenter.java:455)
       at android.support.v17.leanback.widget.RowPresenter.setRowViewSelected(RowPresenter.java:404)
       at com.sgottard.sofa.RowsFragment.setRowViewSelected(RowsFragment.java:329)
       at com.sgottard.sofa.RowsFragment.onRowSelected(RowsFragment.java:230)
       at com.sgottard.sofa.BaseRowFragment$1.onChildViewHolderSelected(BaseRowFragment.java:47)
       at android.support.v17.leanback.widget.GridLayoutManager.dispatchChildSelected(GridLayoutManager.java:873)
       at android.support.v17.leanback.widget.GridLayoutManager.access$200(GridLayoutManager.java:50)
       at android.support.v17.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1437)
       at android.support.v17.leanback.widget.StaggeredGrid.appendVisibleItemToRow(StaggeredGrid.java:393)
       at android.support.v17.leanback.widget.StaggeredGridDefault.appendVisibleItemsWithoutCache(StaggeredGridDefault.java:300)
       at android.support.v17.leanback.widget.StaggeredGrid.appendVisibleItems(StaggeredGrid.java:286)
       at android.support.v17.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:360)
       at android.support.v17.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1625)
       at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:1808)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3011)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.support.v17.leanback.widget.ScaleFrameLayout.onLayout(ScaleFrameLayout.java:137)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14125)
       at android.view.ViewGroup.layout(ViewGroup.java:4404)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1984)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1803)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1047)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4588)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5130)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by philipgiuliani** [comment]
The crash happens because `mCurrentFragment.getVerticalGridView()`` is null.
I fixed it with changing it to the following, but im not sure that everything else will still work fine. At least it seems so. I will test it for a longer time now.

``` java
...
} else if (mCurrentFragment != null && mCurrentFragment instanceof RowsFragment) {
    if (((RowsFragment) mCurrentFragment).getVerticalGridView() != null) { // check that getVerticalGridView is not null
        position = ((RowsFragment) mCurrentFragment).getVerticalGridView().getSelectedPosition();
        toggleTitle();
    }
}
...
```
