### ISSUE TITLE
Crash on Start with Android N. Please fix

### ISSUE THREAD

**Issue by MorzhoviyHren** [dextorer/Sofa#17]
Log and stack trace
  java.lang.IncompatibleClassChangeError: The method 'java.lang.Object android.support.v17.leanback.transition.TransitionHelper.createScene(android.view.ViewGroup, java.lang.Runnable)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.sgottard.sofa.BrowseFragment' appears in /data/data/com.testo.androidtv/files/instant-run/dex/slice-com.github.dextorer-sofa-1.0.0_0335c9765600c53bc126f1578e46b4b7eeaf29a5-classes.dex)
                                                                                   at com.sgottard.sofa.BrowseFragment.onCreateView(BrowseFragment.java:667)
                                                                                   at android.app.Fragment.performCreateView(Fragment.java:2352)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:959)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1149)
                                                                                   at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1251)
                                                                                   at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2311)
                                                                                   at android.app.FragmentController.onCreateView(FragmentController.java:98)
                                                                                   at android.app.Activity.onCreateView(Activity.java:5884)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                   at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
                                                                                   at android.app.Activity.setContentView(Activity.java:2414)
                                                                                   at sdk.androidtv.testo.MainActivity.onCreate(MainActivity.java:42)
                                                                                   at android.app.Activity.performCreate(Activity.java:6664)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

It seens like they changed TransitionHelper sources in 24th sdk

**Comment by philipgiuliani** [comment]
You should switch to Leanback 24.*, it provides the same functionality as Sofa out-of-box with less bugs.
